### ISSUE TITLE
Possible conflit with ACF when uploading image

### ISSUE THREAD

**Issue by denissellu** [inboundnow/cta-retired#140]
<img width="958" alt="screen shot 2015-11-06 at 11 02 46" src="https://cloud.githubusercontent.com/assets/4679839/10995611/08ea8ba4-8476-11e5-9ae9-d7ab9dfe42c4.png">

Only when uploading an image I get that error in the console and the page never saves the loader just spins
![screen shot 2015-11-06 at 11 05 25](https://cloud.githubusercontent.com/assets/4679839/10995666/5b7ed780-8476-11e5-9c97-c852d4d4fb0d.png)

I'm not sure if its this plugin or ACF
When I remove ACF it works but I still get an autosave error
<img width="964" alt="screen shot 2015-11-06 at 11 06 47" src="https://cloud.githubusercontent.com/assets/4679839/10995688/8b3d8d54-8476-11e5-8894-100a5d0457bb.png">
##

**Comment by atwellpub** [comment]
Hi will you provide detailed steps on how to reproduce?
